version: '3.5'

x-args: &default-args
  args:
    POSTGRES_USER: admin
    POSTGRES_PASSWORD: admin
    POSTGRES_HOST: localhost
    POSTGRES_PORT: 5432
    POSTGRES_DB: example
    TABLE_NAME: cats

services:
  postgres:
    container_name: postgres
    build:
      context: './databases'
      <<: *default-args
    ports:
      - "5432:5432"
    networks:
      - net

  bd_filler:
    build:
      context: './bd_filling'
      args:
        DATABASE_CONNECTION_URL: "postgresql+psycopg2://admin:admin@postgres:5432/example"
        # host = postgres is necessarly !
    container_name: bd_filler
    command: >
      bash -c "sleep 5 && python main.py"
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    networks:
      - net
  web:
    build:
      context: './web'
      <<: *default-args
    depends_on:
      - postgres
      - bd_filler
    ports:
      - "5000:5000"
    networks:
      - net

networks:
  net:
    driver: bridge
