version: '3.5'
services:
  postgres:
    container_name: postgres
    build:
      context: './databases'
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=example
    ports:
      - "5432:5432"
    networks:
      - net

  bd_filler:
    build:
      context: './bd_filling'
    container_name: bd_filler
    command: >
      bash -c "python main.py"
    volumes:
      - ./data:/data
    depends_on:
      - postgres
    networks:
      - net
  web:
    build:
      context: './web'
    depends_on:
      - postgres
      - bd_filler
    ports:
      - "5000:5000"
    networks:
      - net

networks:
  net:
    driver: bridge

## TODO:
# argparses to bd_filler/main.py to pass correct PATH to csv
#